
target:'WifeButler' do
platform :ios, '7.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'IQKeyboardManager', '~> 3.2.4'
pod 'SDCycleScrollView', '~> 1.64'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'AlipaySDK-2.0', '~> 15.0.2'

end
